# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'nodeProject'
    organization: '24134252'
    scannerMode: 'cli'
    configMode: 'file'

- script: |
    npm install
  # npm run build
  displayName: 'npm install' # and build'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- script: |
    npm install
  # npm run build
  displayName: 'npm install' # and build'

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'nodeProject'
    organization: '24134252'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: '24134252_NodeProject'
    cliProjectName: 'NodeProject'
    cliSources: '.'
    
- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'